name: SkyCrystals
author: Wolfur
version: 1.0
api-version: 1.13
main: net.twerion.skycrystals.SkyCrystals
depend: [BeastClientPlugin]
commands:
  SkyCrystals:
    description: Main command.
    usage:
  Sc:
    description: Main command.
    usage:
  SkyCrystalsShop:
    description: Shop command.
    usage:
  Scs:
    description: Shop command.
    usage: